// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChETNgn6iDwZOfsLuiUabLJ9LHKxDLhys',
    appId: '1:1089782277064:web:a829cee5ef75b8dd69d6fd',
    messagingSenderId: '1089782277064',
    projectId: 'weathoapp',
    authDomain: 'weathoapp.firebaseapp.com',
    storageBucket: 'weathoapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoIeX5sx0KId_evVrDbfS-DvpbEsSSjf0',
    appId: '1:1089782277064:android:94d01baba5c6e85569d6fd',
    messagingSenderId: '1089782277064',
    projectId: 'weathoapp',
    storageBucket: 'weathoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBfZ2qyEVgvYbFD1qhChJnqEWgtD7HFCc',
    appId: '1:1089782277064:ios:91adcfa3578eb4ca69d6fd',
    messagingSenderId: '1089782277064',
    projectId: 'weathoapp',
    storageBucket: 'weathoapp.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBfZ2qyEVgvYbFD1qhChJnqEWgtD7HFCc',
    appId: '1:1089782277064:ios:91adcfa3578eb4ca69d6fd',
    messagingSenderId: '1089782277064',
    projectId: 'weathoapp',
    storageBucket: 'weathoapp.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChETNgn6iDwZOfsLuiUabLJ9LHKxDLhys',
    appId: '1:1089782277064:web:e819a5895de8e26c69d6fd',
    messagingSenderId: '1089782277064',
    projectId: 'weathoapp',
    authDomain: 'weathoapp.firebaseapp.com',
    storageBucket: 'weathoapp.firebasestorage.app',
  );
}
